<?php
declare(strict_types=1);

namespace MonkeysLegion\Router;

use RuntimeException;

/**
 * Route caching system for production performance.
 */
class RouteCache
{
    public function __construct(
        private string $cacheDir
    ) {
        if (!is_dir($cacheDir) && !mkdir($cacheDir, 0755, true)) {
            throw new RuntimeException("Failed to create cache directory: {$cacheDir}");
        }
    }

    /**
     * Get the cache file path
     */
    private function getCacheFile(): string
    {
        return $this->cacheDir . '/routes.cache.php';
    }

    /**
     * Check if cache exists and is valid
     */
    public function has(): bool
    {
        return file_exists($this->getCacheFile());
    }

    /**
     * Load routes from cache
     */
    public function load(): ?array
    {
        $cacheFile = $this->getCacheFile();

        if (!file_exists($cacheFile)) {
            return null;
        }

        try {
            $data = include $cacheFile;

            if (!is_array($data) || !isset($data['routes'], $data['namedRoutes'])) {
                return null;
            }

            return $data;
        } catch (\Throwable $e) {
            return null;
        }
    }

    /**
     * Save routes to cache
     */
    public function save(array $routes, array $namedRoutes): bool
    {
        $cacheFile = $this->getCacheFile();

        $data = [
            'routes' => $routes,
            'namedRoutes' => $namedRoutes,
            'cached_at' => date('Y-m-d H:i:s'),
        ];

        $content = '<?php' . PHP_EOL . PHP_EOL;
        $content .= '// Route cache generated at ' . date('Y-m-d H:i:s') . PHP_EOL;
        $content .= '// DO NOT EDIT THIS FILE MANUALLY' . PHP_EOL . PHP_EOL;
        $content .= 'return ' . var_export($data, true) . ';' . PHP_EOL;

        return file_put_contents($cacheFile, $content, LOCK_EX) !== false;
    }

    /**
     * Clear the route cache
     */
    public function clear(): bool
    {
        $cacheFile = $this->getCacheFile();

        if (file_exists($cacheFile)) {
            return unlink($cacheFile);
        }

        return true;
    }

    /**
     * Get cache file modification time
     */
    public function getModifiedTime(): ?int
    {
        $cacheFile = $this->getCacheFile();

        if (!file_exists($cacheFile)) {
            return null;
        }

        return filemtime($cacheFile);
    }

    /**
     * Check if cache is stale compared to source files
     */
    public function isStale(array $sourceFiles): bool
    {
        $cacheTime = $this->getModifiedTime();

        if ($cacheTime === null) {
            return true;
        }

        foreach ($sourceFiles as $file) {
            if (file_exists($file) && filemtime($file) > $cacheTime) {
                return true;
            }
        }

        return false;
    }

    /**
     * Get cache statistics
     */
    public function getStats(): array
    {
        $cacheFile = $this->getCacheFile();

        if (!file_exists($cacheFile)) {
            return [
                'exists' => false,
                'size' => 0,
                'modified' => null,
            ];
        }

        return [
            'exists' => true,
            'size' => filesize($cacheFile),
            'modified' => filemtime($cacheFile),
            'path' => $cacheFile,
        ];
    }
}