<?php
declare(strict_types=1);

namespace MonkeysLegion\Router;

use RuntimeException;

/**
 * MonkeysLegion Framework — Router Package
 *
 * Route cache using CompiledRoutes for near-zero startup cost.
 *
 * v2 improvements:
 *  • Stores CompiledRoutes instead of raw arrays.
 *  • Calls opcache_compile_file() for instant warm-up.
 *  • Uses xxh128 integrity hash via hash_file().
 *
 * @copyright 2026 MonkeysCloud Team
 * @license   MIT
 */
final class RouteCache
{
    public function __construct(
        private readonly string $cacheDir,
    ) {
        if (!is_dir($cacheDir) && !mkdir($cacheDir, 0755, true)) {
            throw new RuntimeException("Failed to create cache directory: {$cacheDir}");
        }
    }

    private function cacheFile(): string
    {
        return $this->cacheDir . '/routes.cache.php';
    }

    private function hashFile(): string
    {
        return $this->cacheDir . '/routes.hash';
    }

    /**
     * Check if cache exists and is valid.
     */
    public function has(): bool
    {
        return file_exists($this->cacheFile());
    }

    /**
     * Load compiled routes from cache.
     */
    public function load(): ?CompiledRoutes
    {
        $file = $this->cacheFile();
        if (!file_exists($file)) {
            return null;
        }

        try {
            $data = include $file;
            if (!is_array($data) || !isset($data['static'], $data['dynamic'])) {
                return null;
            }
            return CompiledRoutes::import($data);
        } catch (\Throwable) {
            return null;
        }
    }

    /**
     * Save compiled routes to cache.
     */
    public function save(CompiledRoutes $compiled): bool
    {
        $file = $this->cacheFile();
        $data = $compiled->export();

        $content = "<?php\n\n"
            . "// Route cache — generated " . date('Y-m-d H:i:s') . "\n"
            . "// DO NOT EDIT THIS FILE MANUALLY\n\n"
            . "return " . var_export($data, true) . ";\n";

        $result = file_put_contents($file, $content, LOCK_EX);
        if ($result === false) {
            return false;
        }

        // Warm OPcache
        if (function_exists('opcache_compile_file')) {
            opcache_compile_file($file);
        }

        // Write integrity hash
        $hashAlgo = in_array('xxh128', hash_algos(), true) ? 'xxh128' : 'sha256';
        file_put_contents($this->hashFile(), hash_file($hashAlgo, $file));

        return true;
    }

    /**
     * Clear the cache.
     */
    public function clear(): bool
    {
        $cleared = true;

        foreach ([$this->cacheFile(), $this->hashFile()] as $file) {
            if (file_exists($file) && !unlink($file)) {
                $cleared = false;
            }
        }

        return $cleared;
    }

    /**
     * Check if cache is stale compared to source files.
     *
     * @param list<string> $sourceFiles
     */
    public function isStale(array $sourceFiles): bool
    {
        $cacheFile = $this->cacheFile();
        if (!file_exists($cacheFile)) {
            return true;
        }

        $cacheTime = filemtime($cacheFile);
        foreach ($sourceFiles as $file) {
            if (file_exists($file) && filemtime($file) > $cacheTime) {
                return true;
            }
        }

        return false;
    }

    /**
     * Get cache statistics.
     *
     * @return array{exists: bool, size: int, modified: int|null, path?: string}
     */
    public function getStats(): array
    {
        $file = $this->cacheFile();

        if (!file_exists($file)) {
            return ['exists' => false, 'size' => 0, 'modified' => null];
        }

        return [
            'exists'   => true,
            'size'     => filesize($file),
            'modified' => filemtime($file),
            'path'     => $file,
        ];
    }
}